### ISSUE TITLE
Old selenium version is being installed

### ISSUE THREAD

**Issue by rfominych1** [barancev/webdriver-testng-archetype#3]
<dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>2.53.1</version>
    </dependency>

**Comment by barancev** [comment]
https://github.com/barancev/webdriver-testng-archetype/blob/master/src/main/resources/archetype-resources/pom.xml#L20-L24

Updated in version 4.0 of the archetype.
