### ISSUE TITLE
'getDriver(java.lang.String, org.openqa.selenium.Capabilities)' is deprecated

### ISSUE THREAD

**Issue by rfominych1** [barancev/webdriver-testng-archetype#4]
after manually changing all versions in POM file to latest versions, getting following message from Intellij:

'getDriver(java.lang.String, org.openqa.selenium.Capabilities)' is deprecated

**Comment by barancev** [comment]
Yes, it should be changed to getDriver(URL, Capabilities), I'll fix it in the next archetype version.

**Comment by barancev** [comment]
Fixed in archetype version 4.3
