### ISSUE TITLE
SuiteConfiguration.hasProperty(String name) is incorrect 

### ISSUE THREAD

**Issue by HugWolf** [barancev/webdriver-testng-archetype#5]
I run my test with profile grid.
But test starts in local browser.

After investigation I saw the problem with method SuiteConfiguration.hasProperty(String name) it always sends me 'false'. Maybe method should be like that:
`public boolean hasProperty(String name) { return properties.containsKey(name); }`

Anyway after that change, my tests opens in grid browser

**Comment by barancev** [comment]
Fixed by ed19053ee17a8f2b786e37607a4c14f89225dce6
